name: docs

on:
  push:
    branches:
      - master
    paths:
      - '**/docs.yml'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
          token: ${{ secrets.OSQ_REPO_TOKEN }}
          fetch-depth: 1

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.OSQ_REPO_TOKEN }}
          publish_dir: ./
          commit_message: Sync Main
